# Pytorch autograd Jacobians vs Bmad analytical transfer matrices
In this example, we track single particles through different elements and calculate the Jacobian matrix by using PyTorch autograd. We compare the results with bmad_standard, which uses analytic formulas to calculate the Jacobian. We also test functionalities such as element offsets and tilts. As of now, only transverse transformations are supported.

In [1]:
import torch
from pytao import Tao
torch.set_printoptions(precision= 15, sci_mode=True)

In [2]:
from pathlib import Path

def find_repo(path):
    "Find repository root from the path's parents"
    for path in Path(path).parents:
        # Check whether "path/.git" exists and is a directory
        git_dir = path / ".git"
        if git_dir.is_dir():
            return path

import os
nb_dir = os.getcwd()
# Find the repo root where the script is
repo_path = str(find_repo(nb_dir))
repo_path

'/global/u1/j/jpga/PS_Reconstruction/Bmad-X'

In [3]:
# create incoming particle
from bmadx import Particle
from bmadx import M_ELECTRON

coords = [2e-3,3e-3,-3e-3,-1e-3,2e-3,-2e-3]
coords_t = torch.tensor(coords, dtype=torch.double)
p_in = Particle(*coords_t,
                s = torch.tensor(0.0, dtype=torch.double),
                p0c = torch.tensor(4.0e7, dtype=torch.double),
                mc2 = torch.tensor(M_ELECTRON, dtype=torch.double))
p_in

Particle(x=tensor(2.000000000000000e-03, dtype=torch.float64), px=tensor(3.000000000000000e-03, dtype=torch.float64), y=tensor(-3.000000000000000e-03, dtype=torch.float64), py=tensor(-1.000000000000000e-03, dtype=torch.float64), z=tensor(2.000000000000000e-03, dtype=torch.float64), pz=tensor(-2.000000000000000e-03, dtype=torch.float64), s=tensor(0., dtype=torch.float64), p0c=tensor(4.000000000000000e+07, dtype=torch.float64), mc2=tensor( 5.109989500000000e+05, dtype=torch.float64))

# Drift tests

In [4]:
# Create drift
from bmadx.structures import Drift

d = Drift(L=1.0)
d

Drift(L=1.0)

## Drift one particle test

In [5]:
# Outgoing particle:
from bmadx.track import track_element

p_out = track_element(p_in, d)

# coordinates as tensor:
x_py = torch.hstack(p_out[:6])
x_py

tensor([5.006027114522933e-03, 3.000000000000000e-03, -4.002009038174311e-03,
        -1.000000000000000e-03, 1.994652573892362e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [6]:
# bmad lattice for comparison
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_drift.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out=tao.orbit_at_s(ele=1)

In [7]:
# bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([5.006027114522930e-03, 3.000000000000000e-03, -4.002009038174310e-03,
        -1.000000000000000e-03, 1.994652573892360e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [8]:
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

True

## Drift Jacobian test

In [9]:
# autodiff Jacobian
from torch.autograd.functional import jacobian

f_drift = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), d)[:6]

diff_coords = coords_t.clone().detach().requires_grad_(True)

J = jacobian(f_drift, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 1.000000000000000e+00,  1.002018092527393e+00,  0.000000000000000e+00,
         -3.018117694005117e-06,  0.000000000000000e+00, -3.012081458617107e-03],
        [ 0.000000000000000e+00,  1.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 0.000000000000000e+00, -3.018117694005117e-06,  1.000000000000000e+00,
          1.002010044213542e+00,  0.000000000000000e+00,  1.004027152872369e-03],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 0.000000000000000e+00, -3.012081458617106e-03,  0.000000000000000e+00,
          1.004027152872369e-03,  1.000000000000000e+00,  1.742165247481025e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [10]:
# Bmad analytical Jacobian
drift_tao = tao.matrix(0,1)
mat_tao = torch.tensor(drift_tao['mat6'])
mat_tao

tensor([[ 1.000000000000000e+00,  1.002018092527390e+00,  0.000000000000000e+00,
         -3.018117694005120e-06,  0.000000000000000e+00, -3.012081458617110e-03],
        [ 0.000000000000000e+00,  1.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 0.000000000000000e+00, -3.018117694005120e-06,  1.000000000000000e+00,
          1.002010044213540e+00,  0.000000000000000e+00,  1.004027152872370e-03],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 0.000000000000000e+00, -3.012081458617110e-03,  0.000000000000000e+00,
          1.004027152872370e-03,  1.000000000000000e+00,  1.742165247481030e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [11]:
# is it close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-14)

True

# Quadrupole tests

In [12]:
# Create quad
from bmadx.structures import Quadrupole

q = Quadrupole(L=0.1, K1=10.0)
q

Quadrupole(L=0.1, K1=10.0, NUM_STEPS=1, X_OFFSET=0.0, Y_OFFSET=0.0, TILT=0.0)

## Quadrupole one particle test

In [13]:
# Outgoing particle
p_out = track_element(p_in, q)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.196239719302552e-03, 8.841834264853368e-04, -3.253441973269224e-03,
        -4.100871741572859e-03, 1.999394664225331e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [14]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_quad.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [15]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.196239719302550e-03, 8.841834264853370e-04, -3.253441973269220e-03,
        -4.100871741572860e-03, 1.999394664225330e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [16]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

True

## Quadrupole Jacobian test

In [17]:
# autodiff Jacobian matrix
f_quadrupole = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), q)[:6]

J = jacobian(f_quadrupole, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.503167431875498e-01,  9.853541097581728e-02,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00, -1.924858550317723e-04],
        [-9.833834015386563e-01,  9.503167431875498e-01, -0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.149663908944082e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  1.050519938506054e+00,
          1.018821577510623e-01,  0.000000000000000e+00,  2.569093937337833e-04],
        [-0.000000000000000e+00,  0.000000000000000e+00,  1.016783934355602e+00,
          1.050519938506054e+00,  0.000000000000000e+00,  1.017485822657404e-04],
        [ 8.003290869842023e-05, -1.942507914386516e-04,  1.543324297486644e-04,
          2.595220753974964e-04,  1.000000000000000e+00,  1.756709202142694e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [18]:
# Bmad formula Jacobian
quad_tao = tao.matrix(0,1)
mat_tao = torch.tensor(quad_tao['mat6'])
mat_tao

tensor([[ 9.503167431875500e-01,  9.853541097581731e-02,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00, -1.924858550317720e-04],
        [-9.833834015386560e-01,  9.503167431875500e-01,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.149663908944080e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  1.050519938506050e+00,
          1.018821577510620e-01,  0.000000000000000e+00,  2.569093937337830e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  1.016783934355600e+00,
          1.050519938506050e+00,  0.000000000000000e+00,  1.017485822657410e-04],
        [ 8.003290869842020e-05, -1.942507914386520e-04,  1.543324297486640e-04,
          2.595220753974960e-04,  1.000000000000000e+00,  1.756709202142690e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [19]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-14)

True

## Quadrupole offset test

In [20]:
# Create quad with offsetss
q_off = Quadrupole(L = 0.1,
                   K1 = 10.0,
                   X_OFFSET = 1e-3,
                   Y_OFFSET = -2e-3)
q_off

Quadrupole(L=0.1, K1=10.0, NUM_STEPS=1, X_OFFSET=0.001, Y_OFFSET=-0.002, TILT=0.0)

In [21]:
# Outgoing particle no offset
p_out = track_element(p_in, q)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.196239719302552e-03, 8.841834264853368e-04, -3.253441973269224e-03,
        -4.100871741572859e-03, 1.999394664225331e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [22]:
# Outgoing particle offset
p_out = track_element(p_in, q_off)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.245922976115002e-03, 1.867566828023993e-03, -3.152402096257116e-03,
        -2.067303872861656e-03, 1.999538606428305e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [23]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_quad_offset.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [24]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.245922976115000e-03, 1.867566828023990e-03, -3.152402096257120e-03,
        -2.067303872861660e-03, 1.999538606428300e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [25]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

True

In [26]:
# autodiff Jacobian matrix
f_quadrupole_off = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), q_off)[:6]

J = jacobian(f_quadrupole_off, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.503167431875498e-01,  9.853541097581728e-02,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00, -2.418522933964102e-04],
        [-9.833834015386563e-01,  9.503167431875498e-01, -0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.315328529941612e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  1.050519938506054e+00,
          1.018821577510623e-01,  0.000000000000000e+00,  1.548230633218972e-04],
        [-0.000000000000000e+00,  0.000000000000000e+00,  1.016783934355602e+00,
          1.050519938506054e+00,  0.000000000000000e+00,  6.794497089254226e-05],
        [ 1.128356584705092e-04, -2.427969275195176e-04,  8.604405680959595e-05,
          1.557223347173730e-04,  1.000000000000000e+00,  1.726852196136135e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [27]:
# Bmad formula Jacobian
quad_tao = tao.matrix(0,1)
mat_tao = torch.tensor(quad_tao['mat6'])
mat_tao

tensor([[ 9.503167431875500e-01,  9.853541097581731e-02,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00, -2.418522933964100e-04],
        [-9.833834015386560e-01,  9.503167431875500e-01,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.315328529941610e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  1.050519938506050e+00,
          1.018821577510620e-01,  0.000000000000000e+00,  1.548230633218970e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  1.016783934355600e+00,
          1.050519938506050e+00,  0.000000000000000e+00,  6.794497089254231e-05],
        [ 1.128356584705090e-04, -2.427969275195180e-04,  8.604405680959591e-05,
          1.557223347173730e-04,  1.000000000000000e+00,  1.726852196136140e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [28]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-14)

True

## Quadrupole tilt test (transverse rotation)

In [29]:
# Create quadrupole with tilt
q_tilt = Quadrupole(L = 0.1,
                    K1 = 10.0,
                    TILT = 0.3)
q_tilt

Quadrupole(L=0.1, K1=10.0, NUM_STEPS=1, X_OFFSET=0.0, Y_OFFSET=0.0, TILT=0.3)

In [30]:
# Outgoing particle no tilt
p_out = track_element(p_in, q)
x_py = torch.hstack(p_out[:6])
x_py

tensor([2.196239719302552e-03, 8.841834264853368e-04, -3.253441973269224e-03,
        -4.100871741572859e-03, 1.999394664225331e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [31]:
# Outgoing particle tilt
p_out = track_element(p_in, q_tilt)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.300431812756860e-03, 2.982152956166943e-03, -3.286310353406088e-03,
        -4.782331681936468e-03, 1.999046404985869e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [32]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_quad_tilt.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [33]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.300431812756860e-03, 2.982152956166940e-03, -3.286310353406090e-03,
        -4.782331681936470e-03, 1.999046404985870e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [34]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

True

In [35]:
# autodiff Jacobian matrix
f_quadrupole_tilt = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), q_tilt)[:6]

J = jacobian(f_quadrupole_tilt, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.590677079347456e-01,  9.882768970959287e-02, -2.828949002336301e-02,
         -9.448576885006041e-04,  0.000000000000000e+00, -2.987178598581627e-04],
        [-8.087044026377975e-01,  9.590677079347456e-01, -5.646897158716462e-01,
         -2.828949002336301e-02,  0.000000000000000e+00,  5.996905851096495e-05],
        [-2.828949002336301e-02, -9.448576885006041e-04,  1.041768973758858e+00,
          1.015898790172867e-01,  0.000000000000000e+00,  2.923927872640420e-04],
        [-5.646897158716461e-01, -2.828949002336301e-02,  8.421049354547430e-01,
          1.041768973758858e+00,  0.000000000000000e+00,  1.781243721626206e-04],
        [ 2.398790860688291e-05, -3.005205973357010e-04,  2.310403623486719e-04,
          2.950173386467863e-04,  1.000000000000000e+00,  1.827533631132711e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [36]:
# Bmad formula Jacobian
quad_tao = tao.matrix(0,1)
mat_tao = torch.tensor(quad_tao['mat6'])
mat_tao

tensor([[ 9.590677079347460e-01,  9.882768970959289e-02, -2.828949002336300e-02,
         -9.448576885006040e-04,  0.000000000000000e+00, -2.987178598581630e-04],
        [-8.087044026377980e-01,  9.590677079347460e-01, -5.646897158716460e-01,
         -2.828949002336300e-02,  0.000000000000000e+00,  5.996905851096470e-05],
        [-2.828949002336300e-02, -9.448576885006040e-04,  1.041768973758860e+00,
          1.015898790172870e-01,  0.000000000000000e+00,  2.923927872640420e-04],
        [-5.646897158716460e-01, -2.828949002336300e-02,  8.421049354547430e-01,
          1.041768973758860e+00,  0.000000000000000e+00,  1.781243721626220e-04],
        [ 2.398790860688290e-05, -3.005205973357010e-04,  2.310403623486720e-04,
          2.950173386467860e-04,  1.000000000000000e+00,  1.827533631132710e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [37]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-14)

True

# Crab_Cavity tests

In [38]:
# Create cavity
from bmadx import CrabCavity

cav = CrabCavity(L=0.2,
                 VOLTAGE=1e4,
                 PHI0=0.5,
                 RF_FREQUENCY=1e9)
cav

CrabCavity(L=0.2, VOLTAGE=10000.0, PHI0=0.5, RF_FREQUENCY=1000000000.0, NUM_STEPS=1, X_OFFSET=0.0, Y_OFFSET=0.0, TILT=0.0)

## Crab_cavity one particle test

In [39]:
# Outgoing particle
p_out = track_element(p_in, cav)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.600159503009856e-03, 2.989525785200116e-03, -3.200403013811110e-03,
        -1.000000000000000e-03, 1.998933450470348e-03, -2.012044669173099e-03],
       dtype=torch.float64)

In [40]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_crab_cavity.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [41]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.600159485837890e-03, 2.989525613829410e-03, -3.200403013811020e-03,
        -1.000000000000000e-03, 1.998933450521790e-03, -2.012044668826460e-03],
       dtype=torch.float64)

In [42]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-7)

True

In [43]:
# close to Tao result?
torch.isclose(x_py, x_tao, atol=0, rtol=1.0e-8)

tensor([ True, False,  True,  True,  True,  True])

## Crab_cavity Jacobian test

In [44]:
# autodiff Jacobian matrix
f_crab_cavity = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), cav)[:6]

J = jacobian(f_crab_cavity, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 1.000001571489388e+00,  2.004051338856653e-01,  0.000000000000000e+00,
         -6.552534052264527e-07, -5.246100940167111e-04, -6.013813103820471e-04],
        [ 0.000000000000000e+00,  1.000001576957398e+00,  0.000000000000000e+00,
         -5.256524659788450e-07, -5.235440739575950e-03, -8.949162872176154e-08],
        [-5.256651057680826e-07, -6.552540421507948e-07,  1.000000000000000e+00,
          2.004032150230133e-01,  2.637597029868803e-09,  2.008080032283205e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00, -0.000000000000000e+00,  0.000000000000000e+00],
        [-9.289874897604998e-08, -6.013816504874850e-04, -0.000000000000000e+00,
          2.008080022802770e-04,  1.000001569699991e+00,  3.483769060576968e-05],
        [-5.235440749927688e-03, -5.246038241196926e-04, -0.000000000000000e+00,
          2.643031443043208e-09,  1.058650459477272e-05,  1.000001579115604e+00]],
       dtype=torch.fl

In [45]:
# Bmad formula Jacobian
cav_tao = tao.matrix(0,1)
mat_tao = torch.tensor(cav_tao['mat6'])
mat_tao

tensor([[ 1.000001571489250e+00,  2.004051338854580e-01,  0.000000000000000e+00,
         -6.552533864741590e-07, -5.246100789744220e-04, -6.013812931745790e-04],
        [ 0.000000000000000e+00,  1.000001576957350e+00,  0.000000000000000e+00,
         -5.256524508556580e-07, -5.235440588950670e-03, -8.949162614705570e-08],
        [-5.256650906433550e-07, -6.552540233985010e-07,  1.000000000000000e+00,
          2.004032150229270e-01,  2.637614285255740e-09,  2.008080032280910e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [-9.289874576351840e-08, -6.013816332799530e-04,  0.000000000000000e+00,
          2.008080022800390e-04,  1.000001569699860e+00,  3.483769050266000e-05],
        [-5.235440599302410e-03, -5.246038090789391e-04,  0.000000000000000e+00,
          2.643048788126590e-09,  1.058667780267670e-05,  1.000001579115560e+00]],
       dtype=torch.fl

In [46]:
# close to Tao result up to 13th decimal place
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-4)

True

In [47]:
# but not up to 14th decimal place
torch.isclose(mat_py, mat_tao, atol=0, rtol=1e-5)

tensor([[ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False,  True]])

## Crab_cavity offset test

In [48]:
# Cavity with offsets
cav_off = CrabCavity(L=0.2,
                     VOLTAGE=1e4,
                     PHI0=0.5,
                     RF_FREQUENCY=1e9,
                     X_OFFSET=1e-3,
                     Y_OFFSET=-2e-3)
cav_off

CrabCavity(L=0.2, VOLTAGE=10000.0, PHI0=0.5, RF_FREQUENCY=1000000000.0, NUM_STEPS=1, X_OFFSET=0.001, Y_OFFSET=-0.002, TILT=0.0)

In [49]:
# Outgoing particle no offset
p_out = track_element(p_in, cav)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.600159503009856e-03, 2.989525785200116e-03, -3.200403013811110e-03,
        -1.000000000000000e-03, 1.998933450470348e-03, -2.012044669173099e-03],
       dtype=torch.float64)

In [50]:
# Outgoing particle offset
p_out = track_element(p_in, cav_off)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.600157931528713e-03, 2.989525785200116e-03, -3.200402488148762e-03,
        -1.000000000000000e-03, 1.998933543368366e-03, -2.006809228425473e-03],
       dtype=torch.float64)

In [51]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_crab_cavity_offset.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [52]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.600157914356880e-03, 2.989525613829410e-03, -3.200402488148690e-03,
        -1.000000000000000e-03, 1.998933543419810e-03, -2.006809228229520e-03],
       dtype=torch.float64)

In [53]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-7)

True

In [54]:
# close to Tao result?
torch.isclose(x_py, x_tao, atol=0, rtol=1.0e-8)

tensor([ True, False,  True,  True,  True,  True])

In [55]:
# autodiff Jacobian matrix
f_crab_cavity_off = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), cav_off)[:6]

J = jacobian(f_crab_cavity_off, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 1.000001571472898e+00,  2.004046082062692e-01,  0.000000000000000e+00,
         -6.552482567216043e-07, -5.246059606096404e-04, -6.013781607107568e-04],
        [ 0.000000000000000e+00,  1.000001576957398e+00,  0.000000000000000e+00,
         -5.256524659788450e-07, -5.235440739575950e-03, -8.949162872176154e-08],
        [-5.256595900031537e-07, -6.552486167910892e-07,  1.000000000000000e+00,
          2.004026893590357e-01,  2.175539466651803e-09,  2.008069496751906e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00, -0.000000000000000e+00,  0.000000000000000e+00],
        [-9.289728709737649e-08, -6.013785012326269e-04, -0.000000000000000e+00,
          2.008069488994388e-04,  1.000001570461304e+00,  3.483741139091059e-05],
        [-5.235440745428065e-03, -5.246024376227188e-04, -0.000000000000000e+00,
          2.181016073880466e-09,  5.984882352954397e-06,  1.000001578177490e+00]],
       dtype=torch.fl

In [56]:
# Bmad formula Jacobian
cav_tao = tao.matrix(0,1)
mat_tao = torch.tensor(cav_tao['mat6'])
mat_tao

tensor([[ 1.000001571472760e+00,  2.004046082060770e-01,  0.000000000000000e+00,
         -6.552482379674740e-07, -5.246059455449890e-04, -6.013781435035600e-04],
        [ 0.000000000000000e+00,  1.000001576957350e+00,  0.000000000000000e+00,
         -5.256524508556580e-07, -5.235440588950670e-03, -8.949162614705570e-08],
        [-5.256595748787440e-07, -6.552485980369581e-07,  1.000000000000000e+00,
          2.004026893589650e-01,  2.175549162632720e-09,  2.008069496749920e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [-9.289728388493930e-08, -6.013784840253660e-04,  0.000000000000000e+00,
          2.008069488992310e-04,  1.000001570461170e+00,  3.483741128781100e-05],
        [-5.235440594802780e-03, -5.246024225592880e-04,  0.000000000000000e+00,
          2.181025859838670e-09,  5.984980272803050e-06,  1.000001578177450e+00]],
       dtype=torch.fl

In [57]:
# close to Tao result up to 13th decimal place
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-4)

True

In [58]:
# but not up to 14th decimal place
torch.isclose(mat_py, mat_tao, atol=0, rtol=1e-5)

tensor([[ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False,  True]])

## Crab_cavity tilt test

In [59]:
# Cavity with tilts
cav_tilt = CrabCavity(L=0.2,
                      VOLTAGE=1e4,
                      PHI0=0.5,
                      RF_FREQUENCY=1e9,
                      TILT=0.3)
cav_tilt

CrabCavity(L=0.2, VOLTAGE=10000.0, PHI0=0.5, RF_FREQUENCY=1000000000.0, NUM_STEPS=1, X_OFFSET=0.0, Y_OFFSET=0.0, TILT=0.3)

In [60]:
# Outgoing particle no offset
p_out = track_element(p_in, cav)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.600159503009856e-03, 2.989525785200116e-03, -3.200403013811110e-03,
        -1.000000000000000e-03, 1.998933450470348e-03, -2.012044669173099e-03],
       dtype=torch.float64)

In [61]:
# Outgoing particle offset and tilt
p_out = track_element(p_in, cav_tilt)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.600204778962090e-03, 2.989993600406731e-03, -3.200712636808565e-03,
        -1.003095342122277e-03, 1.998933093429908e-03, -2.006710147677921e-03],
       dtype=torch.float64)

In [62]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_crab_cavity_tilt.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [63]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.600204762557230e-03, 2.989993436690040e-03, -3.200712641883060e-03,
        -1.003095392765780e-03, 1.998933093473960e-03, -2.006710147484760e-03],
       dtype=torch.float64)

In [64]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-7)

True

In [65]:
# close to Tao result?
torch.isclose(x_py, x_tao, atol=0, rtol=1.0e-8)

tensor([ True, False,  True, False,  True,  True])

In [66]:
# autodiff Jacobian matrix
f_crab_cavity_tilt = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), cav_tilt)[:6]

J = jacobian(f_crab_cavity_tilt, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 1.000001501520052e+00,  2.004045849247234e-01,  4.644745816295703e-07,
         -6.073329524777793e-07, -5.011747580192464e-04, -6.014246074929699e-04],
        [ 0.000000000000000e+00,  1.000001506524944e+00,  0.000000000000000e+00,
         -5.021749813760579e-07, -5.001607575171653e-03, -8.549461838918180e-08],
        [-5.037361184290212e-07, -6.073336060452572e-07,  9.999998441761583e-01,
          2.004026493081451e-01, -1.550277786188271e-04,  2.011150437638263e-04],
        [ 0.000000000000000e+00,  4.660227761466018e-07,  0.000000000000000e+00,
          9.999998446590745e-01, -1.547178529322680e-03, -2.644658461431483e-08],
        [-8.875266924563281e-08, -6.014249329362829e-04, -2.745441784728740e-08,
          2.011149416027625e-04,  1.000001344699341e+00,  3.483830346577687e-05],
        [-5.001607580681043e-03, -5.011714382641526e-04, -1.547178531026935e-03,
         -1.550267411292252e-04,  5.897796624455826e-06,  1.000001352386358e+00]],
       dtype=torch.fl

In [67]:
cav_tao = tao.matrix(0,1)
mat_tao = torch.tensor(cav_tao['mat6'])
mat_tao

tensor([[ 1.000001501519930e+00,  2.004045849245440e-01,  4.644745428827870e-07,
         -6.073329536365750e-07, -5.011747436284050e-04, -6.014245910543570e-04],
        [ 0.000000000000000e+00,  1.000001506524900e+00,  0.000000000000000e+00,
         -5.021749668876470e-07, -5.001607431273830e-03, -8.549461592946949e-08],
        [-5.037361294202289e-07, -6.073336071971140e-07,  9.999998441761550e-01,
          2.004026493080920e-01, -1.550277741487870e-04,  2.011150488485470e-04],
        [ 0.000000000000000e+00,  4.660227627684140e-07,  0.000000000000000e+00,
          9.999998446590790e-01, -1.547178484809870e-03, -2.644658385343720e-08],
        [-8.875266625062010e-08, -6.014249164976120e-04, -2.745441692082140e-08,
          2.011149466874840e-04,  1.000001344699210e+00,  3.483830337748740e-05],
        [-5.001607436783220e-03, -5.011714238744080e-04, -1.547178486514120e-03,
         -1.550267366593520e-04,  5.897893119477580e-06,  1.000001352386320e+00]],
       dtype=torch.fl

In [68]:
torch.isclose(mat_py, mat_tao, atol=0, rtol=1.0e-13)

tensor([[False, False, False, False, False, False],
        [ True,  True,  True, False, False, False],
        [False, False,  True, False, False, False],
        [ True, False,  True,  True, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False,  True]])

In [69]:
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-4)

True

In [70]:
torch.isclose(mat_py, mat_tao, atol=0, rtol=1.0e-5)

tensor([[ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False,  True]])

In [71]:
# Something is wrong with the Jacobian matrix of a tilted cavity. Currently debuging.

# RF_Cavity tests

In [72]:
# Create cavity
from bmadx import RFCavity

cav = RFCavity(L=0.2,
               VOLTAGE=1e4,
               PHI0=0.5,
               RF_FREQUENCY=1e9)
cav

RFCavity(L=0.2, VOLTAGE=10000.0, PHI0=0.5, RF_FREQUENCY=1000000000.0, NUM_STEPS=1, X_OFFSET=0.0, Y_OFFSET=0.0, TILT=0.0)

## RF_Cavity one particle test

In [73]:
# Outgoing particle
p_out = track_element(p_in, cav)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.601208578941774e-03, 3.000000000000000e-03, -3.200402859647258e-03,
        -1.000000000000000e-03, 1.998930328796947e-03, -2.010475072419949e-03],
       dtype=torch.float64)

In [74]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_rf_cavity.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [75]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.601208578941770e-03, 3.000000000000000e-03, -3.200402859647260e-03,
        -1.000000000000000e-03, 1.998930328796950e-03, -2.010475072419950e-03],
       dtype=torch.float64)

In [76]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

True

## RF_Cavity Jacobian test

In [77]:
# autodiff Jacobian matrix
f_rf_cavity = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), cav)[:6]

J = jacobian(f_rf_cavity, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 1.000000000000000e+00,  2.004046705463930e-01,  0.000000000000000e+00,
         -6.036330450442983e-07,  1.577102406617731e-06, -6.024226175949689e-04],
        [ 0.000000000000000e+00,  1.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 0.000000000000000e+00, -6.036330450442982e-07,  1.000000000000000e+00,
          2.004030608582729e-01, -5.257008022059102e-07,  2.008075391983230e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 0.000000000000000e+00, -6.024226155237540e-04,  0.000000000000000e+00,
          2.008075385079180e-04,  9.999999053429351e-01,  3.484386392945851e-05],
        [ 0.000000000000000e+00,  1.577103892075475e-06,  0.000000000000000e+00,
         -5.257012973584918e-07, -5.235869418127461e-03,  9.999999122191349e-01]],
       dtype=torch.fl

In [78]:
# Bmad formula Jacobian
quad_tao = tao.matrix(0,1)
mat_tao = torch.tensor(quad_tao['mat6'])
mat_tao

tensor([[ 1.000000000000000e+00,  2.004046705463930e-01,  0.000000000000000e+00,
         -6.036330450442980e-07,  1.577102406617730e-06, -6.024226175949690e-04],
        [ 0.000000000000000e+00,  1.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 0.000000000000000e+00, -6.036330450442980e-07,  1.000000000000000e+00,
          2.004030608582730e-01, -5.257008022059100e-07,  2.008075391983230e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 0.000000000000000e+00, -6.024226155237540e-04,  0.000000000000000e+00,
          2.008075385079180e-04,  9.999999053429350e-01,  3.484386392945810e-05],
        [ 0.000000000000000e+00,  1.577103892075480e-06,  0.000000000000000e+00,
         -5.257012973584920e-07, -5.235869418127460e-03,  9.999999122191350e-01]],
       dtype=torch.fl

In [79]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-13)

True

## RF_Cavity offset test

In [80]:
# RF cav with offsets
cav_off = RFCavity(L=0.2,
                   VOLTAGE = 1e4,
                   PHI0 = 0.5,
                   RF_FREQUENCY = 1e9,
                   X_OFFSET = 1e-3,
                   Y_OFFSET = -2e-3)
cav_off

RFCavity(L=0.2, VOLTAGE=10000.0, PHI0=0.5, RF_FREQUENCY=1000000000.0, NUM_STEPS=1, X_OFFSET=0.001, Y_OFFSET=-0.002, TILT=0.0)

In [81]:
# Outgoing particle no offset
p_out = track_element(p_in, cav)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.601208578941774e-03, 3.000000000000000e-03, -3.200402859647258e-03,
        -1.000000000000000e-03, 1.998930328796947e-03, -2.010475072419949e-03],
       dtype=torch.float64)

In [82]:
# Outgoing particle offset
p_out = track_element(p_in, cav_off)
x_py = torch.hstack(p_out[:6])
x_py

tensor([2.601208578941774e-03, 3.000000000000000e-03, -3.200402859647258e-03,
        -1.000000000000000e-03, 1.998930328796947e-03, -2.010475072419949e-03],
       dtype=torch.float64)

In [83]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_rf_cavity_offset.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [84]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.601208578941770e-03, 3.000000000000000e-03, -3.200402859647260e-03,
        -1.000000000000000e-03, 1.998930328796950e-03, -2.010475072419950e-03],
       dtype=torch.float64)

In [85]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

True

## RF_Cavity tilt test

In [86]:
# RF cav with tilt
cav_tilt = RFCavity(L=0.2,
                    VOLTAGE=1e4,
                    PHI0=0.5,
                    RF_FREQUENCY=1e9,
                    TILT=0.3)
cav_tilt

RFCavity(L=0.2, VOLTAGE=10000.0, PHI0=0.5, RF_FREQUENCY=1000000000.0, NUM_STEPS=1, X_OFFSET=0.0, Y_OFFSET=0.0, TILT=0.3)

In [87]:
# Outgoing particle no offset
p_out = track_element(p_in, cav)
x_py = torch.hstack(p_out[:6])
x_py

tensor([2.601208578941774e-03, 3.000000000000000e-03, -3.200402859647258e-03,
        -1.000000000000000e-03, 1.998930328796947e-03, -2.010475072419949e-03],
       dtype=torch.float64)

In [88]:
# Outgoing particle tilt
p_out = track_element(p_in, cav_tilt)
x_py = torch.hstack(p_out[:6])
x_py

tensor([2.601208578941774e-03, 3.000000000000000e-03, -3.200402859647258e-03,
        -1.000000000000000e-03, 1.998930328796947e-03, -2.010475072419949e-03],
       dtype=torch.float64)

In [89]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_rf_cavity_tilt.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [90]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.601208578941770e-03, 3.000000000000000e-03, -3.200402859647260e-03,
        -1.000000000000000e-03, 1.998930328796950e-03, -2.010475072419950e-03],
       dtype=torch.float64)

In [91]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

True

# SBend tests

## Body Only

In [92]:
# Create bend
from bmadx import SBend, PI

body = SBend(L = 0.1, 
             P0C = p_in.p0c, 
             G = 0.5
            )
body

SBend(L=0.1, P0C=tensor(4.000000000000000e+07, dtype=torch.float64), G=0.5, DG=0.0, E1=0.0, E2=0.0, FINT=0.0, HGAP=0.0, FINTX=0.0, HGAPX=0.0, FRINGE_AT='both_ends', FRINGE_TYPE='linear_edge', TILT=0.0)

### One particle test

In [93]:
# Outgoing particle
p_out = track_element(p_in, body)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.293265789408971e-03, 2.846062876104508e-03, -3.100308492708611e-03,
        -1.000000000000000e-03, 1.892091543991378e-03, -2.000000000000002e-03],
       dtype=torch.float64)

In [94]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_bend.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [95]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.293265789408970e-03, 2.846062876104720e-03, -3.100308492708610e-03,
        -1.000000000000000e-03, 1.892091543991380e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [96]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-13)

True

### Jacobian test

In [97]:
f_bend = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), body)[:6]
J = jacobian(f_bend, diff_coords)

In [98]:
# Jacobian matrix
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.988927899621565e-01,  1.002673052535997e-01,  0.000000000000000e+00,
          2.217963569799612e-06,  0.000000000000000e+00,  2.213527642660013e-03],
        [-2.498958463533967e-02,  9.986000216569765e-01,  0.000000000000000e+00,
          5.007957932966325e-05,  0.000000000000000e+00,  4.997942017100392e-02],
        [-5.007955670508429e-05, -2.806485998782949e-06,  1.000000000000000e+00,
          1.003085933786816e-01,  0.000000000000000e+00,  1.004687301118691e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [-4.997939759167412e-02, -2.800873026785381e-03, -0.000000000000000e+00,
          1.004687301118691e-04,  1.000000000000000e+00, -2.428444372251648e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [99]:
# Bmad Jacobian
bend_tao = tao.matrix(0,1)
mat_tao = torch.tensor(bend_tao['mat6'])
mat_tao

tensor([[ 9.988927899621560e-01,  1.002673052536000e-01,  0.000000000000000e+00,
          2.217963569799610e-06,  0.000000000000000e+00,  2.213527642660010e-03],
        [-2.498958463533920e-02,  9.986000216569770e-01,  0.000000000000000e+00,
          5.007957932966350e-05,  0.000000000000000e+00,  4.997942017100410e-02],
        [-5.007955670508430e-05, -2.806485998782950e-06,  1.000000000000000e+00,
          1.003085933786820e-01,  0.000000000000000e+00,  1.004687301118690e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          1.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [-4.997939759167410e-02, -2.800873026785380e-03,  0.000000000000000e+00,
          1.004687301118690e-04,  1.000000000000000e+00, -2.428444372254420e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [100]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-11)

True

### One particle test with tilt (y-axis orientation)

In [101]:
body_y = SBend(
    L = 0.1, 
    P0C = p_in.p0c, 
    G = 0.5,
    TILT=PI/2
    )

In [102]:
# Outgoing particle
p_out = track_element(p_in, body_y)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.300144230639417e-03, 3.000000000000000e-03, -3.101269254186561e-03,
        -1.023990242298472e-03, 2.151986541139364e-03, -2.000000000000002e-03],
       dtype=torch.float64)

In [103]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_bend_y.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [104]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.300144230639420e-03, 3.000000000000000e-03, -3.101269254186560e-03,
        -1.023990242298450e-03, 2.151986541139360e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [105]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-13)

True

### One particle test (linear fringe)

In [106]:
bend_linear_fringe = SBend(L = 0.1,
             P0C = p_in.p0c,
             G = 0.5,
             DG = 0.0,
             E1 = 0.2,
             E2 = 0.3,
             FINT = 0.05,
             HGAP = 0.03,
             FINTX = 0.08,
             HGAPX = 0.01, 
             FRINGE_AT = "both_ends",
             FRINGE_TYPE = "linear_edge"
            )

In [107]:
# Outgoing particle
p_out = track_element(p_in, bend_linear_fringe)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.313591611322499e-03, 3.406339794786446e-03, -3.070057696037041e-03,
        -2.251095234844629e-04, 1.891547445147787e-03, -2.000000000000002e-03],
       dtype=torch.float64)

In [108]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_bend_linear_both_ends.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [109]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.313591611322500e-03, 3.406339794786520e-03, -3.070057696037040e-03,
        -2.251095234844630e-04, 1.891547445147790e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [110]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-13)

True

## Soft fringe entrance

In [111]:
# Create bend
soft = SBend(L = 0.1,
             P0C = p_in.p0c,
             G = 0.5,
             DG = 0.0,
             E1 = 0.02,
             E2 = 0.0,
             FINT = 0.5,
             HGAP = 0.03,
             FINTX = 0,
             HGAPX = 0,
             FRINGE_AT = "entrance_end",
             FRINGE_TYPE = "soft_edge_only"
            )
soft

SBend(L=0.1, P0C=tensor(4.000000000000000e+07, dtype=torch.float64), G=0.5, DG=0.0, E1=0.02, E2=0.0, FINT=0.5, HGAP=0.03, FINTX=0, HGAPX=0, FRINGE_AT='entrance_end', FRINGE_TYPE='soft_edge_only', TILT=0.0)

### One particle test

In [112]:
# Outgoing particle
p_out = track_element(p_in, soft)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.291914531215035e-03, 2.846095539157815e-03, -3.102567377060580e-03,
        -1.022520040080160e-03, 1.894223854303920e-03, -2.000000000000002e-03],
       dtype=torch.float64)

In [113]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_bend_soft_ent.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [114]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.291914531215030e-03, 2.846095539157940e-03, -3.102567377060580e-03,
        -1.022520040080160e-03, 1.894223854303920e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [115]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=1e-12, rtol = 1e-14)

True

### Jacobian test

In [116]:
f_bend = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), soft)[:6]
J = jacobian(f_bend, diff_coords)

In [117]:
# Jacobian matrix
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.988927916011799e-01,  1.002672398944702e-01,  1.698659358077027e-08,
          2.267909082757021e-06,  0.000000000000000e+00,  2.890482410545297e-03],
        [-2.498958463533991e-02,  9.986000216535417e-01,  3.835422098105090e-07,
          5.120737463423251e-05,  0.000000000000000e+00,  4.996248682483319e-02],
        [-5.120735150492490e-05, -2.869688057667190e-06,  1.000751308898336e+00,
          1.003085325135935e-01,  0.000000000000000e+00,  1.049600030821984e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  7.489979959919840e-03,
          1.000000000000000e+00,  0.000000000000000e+00,  2.256517042100233e-05],
        [-4.997939873912759e-02, -2.123164789675154e-03, -2.179571558510011e-05,
          1.027312275893518e-04,  1.000000000000000e+00, -6.229124242425621e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [118]:
# Bmad Jacobian
bend_tao = tao.matrix(0,1)
mat_tao = torch.tensor(bend_tao['mat6'])
mat_tao

tensor([[ 9.988927916011801e-01,  1.002672398944700e-01,  1.698659358077030e-08,
          2.267909082757020e-06,  0.000000000000000e+00,  2.890482410545300e-03],
        [-2.498958463533910e-02,  9.986000216535420e-01,  3.835422098105100e-07,
          5.120737463423270e-05,  0.000000000000000e+00,  4.996248682483330e-02],
        [-5.120735150492490e-05, -2.869688057667190e-06,  1.000751308898340e+00,
          1.003085325135940e-01,  0.000000000000000e+00,  1.049600030821980e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  7.489979959919840e-03,
          1.000000000000000e+00,  0.000000000000000e+00,  2.256517042100230e-05],
        [-4.997939873912760e-02, -2.123164789675150e-03, -2.179571558510010e-05,
          1.027312275893520e-04,  1.000000000000000e+00, -6.229124242425620e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [119]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-13)

True

## Soft fringe entrance and exit

In [120]:
# Create bend
soft2 = SBend(L = 0.1,
              P0C = p_in.p0c,
              G = 0.5,
              DG = 0.0,
              E1 = 0.02,
              E2 = 0.03,
              FINT = 0.5,
              HGAP = 0.03,
              FINTX = 0.6,
              HGAPX = 0.04,
              FRINGE_AT = "both_ends",
              FRINGE_TYPE = "soft_edge_only"
             )
soft2

SBend(L=0.1, P0C=tensor(4.000000000000000e+07, dtype=torch.float64), G=0.5, DG=0.0, E1=0.02, E2=0.03, FINT=0.5, HGAP=0.03, FINTX=0.6, HGAPX=0.04, FRINGE_AT='both_ends', FRINGE_TYPE='soft_edge_only', TILT=0.0)

### One particle test

In [121]:
# Outgoing particle
p_out = track_element(p_in, soft2)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.295377457066739e-03, 2.846095539157815e-03, -3.102567377060580e-03,
        -1.059808141776569e-03, 1.889344043629332e-03, -2.000000000000002e-03],
       dtype=torch.float64)

In [122]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_bend_soft_both_ends.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [123]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.295377457066740e-03, 2.846095539157940e-03, -3.102567377060580e-03,
        -1.059808141776570e-03, 1.889344043629330e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [124]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=1e-12, rtol = 1e-14)

True

### Jacobian test

In [125]:
f_bend = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), soft2)[:6]
J = jacobian(f_bend, diff_coords)

In [126]:
# Jacobian matrix
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.988927916011799e-01,  1.002672398944702e-01,  1.698659358077027e-08,
          2.267909082757021e-06,  0.000000000000000e+00,  1.155549619110725e-03],
        [-2.498958463533991e-02,  9.986000216535417e-01,  3.835422098105090e-07,
          5.120737463423251e-05,  0.000000000000000e+00,  4.996248682483319e-02],
        [-5.120735150492490e-05, -2.869688057667190e-06,  1.000751308898336e+00,
          1.003085325135935e-01,  0.000000000000000e+00,  1.049600030821984e-04],
        [-6.148621818486901e-07, -3.445721382783641e-08,  1.950630408513815e-02,
          1.001204434936523e+00,  0.000000000000000e+00,  6.118828432483073e-05],
        [-4.993604157604797e-02, -3.855668605549497e-03, -5.918727938082297e-05,
          9.889457585378702e-05,  1.000000000000000e+00, -1.391975410521363e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [127]:
# Bmad Jacobian
bend_tao = tao.matrix(0,1)
mat_tao = torch.tensor(bend_tao['mat6'])
mat_tao

tensor([[ 9.988927916011801e-01,  1.002672398944700e-01,  1.698659358077030e-08,
          2.267909082757020e-06,  0.000000000000000e+00,  1.155549619110730e-03],
        [-2.498958463533910e-02,  9.986000216535420e-01,  3.835422098105100e-07,
          5.120737463423270e-05,  0.000000000000000e+00,  4.996248682483330e-02],
        [-5.120735150492490e-05, -2.869688057667190e-06,  1.000751308898340e+00,
          1.003085325135940e-01,  0.000000000000000e+00,  1.049600030821980e-04],
        [-6.148621818486900e-07, -3.445721382783640e-08,  1.950630408513810e-02,
          1.001204434936520e+00,  0.000000000000000e+00,  6.118828432483070e-05],
        [-4.993604157604800e-02, -3.855668605549500e-03, -5.918727938082300e-05,
          9.889457585378700e-05,  1.000000000000000e+00, -1.391975410521580e-04],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [128]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-12)

True

## Hard fringe entrance

In [129]:
# Create bend
hard = SBend(L = 0.1,
             P0C = p_in.p0c,
             G = 0.5,
             DG = 0.0,
             E1 = 0.02,
             E2 = 0.0,
             FINT = 0.0,
             HGAP = 0.00,
             FINTX = 0,
             HGAPX = 0,
             FRINGE_AT = "entrance_end",
             FRINGE_TYPE = "hard_edge_only"
            )
hard

SBend(L=0.1, P0C=tensor(4.000000000000000e+07, dtype=torch.float64), G=0.5, DG=0.0, E1=0.02, E2=0.0, FINT=0.0, HGAP=0.0, FINTX=0, HGAPX=0, FRINGE_AT='entrance_end', FRINGE_TYPE='hard_edge_only', TILT=0.0)

### One particle test

In [130]:
# Outgoing particle
p_out = track_element(p_in, hard)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.297526317363004e-03, 2.866006011835172e-03, -3.096847685389165e-03,
        -9.654847763270308e-04, 1.891932940825597e-03, -2.000000000000002e-03],
       dtype=torch.float64)

In [131]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_bend_hard_ent.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [132]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.297526317363000e-03, 2.866006011835170e-03, -3.096847685389160e-03,
        -9.654847763270310e-04, 1.891919380637490e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [133]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=1e-12, rtol = 1e-5)

True

### Jacobian test

In [134]:
f_bend = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), hard)[:6]
J = jacobian(f_bend, diff_coords)

In [135]:
# Jacobian matrix
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.998962570786490e-01,  1.002675260014650e-01, -1.503457016141090e-03,
          2.199767517128926e-06,  0.000000000000000e+00,  2.209264164503285e-03],
        [-1.500165222074242e-02,  9.985994918154745e-01,  2.219540412090482e-05,
          4.895157360673543e-05,  0.000000000000000e+00,  4.997945455841134e-02],
        [-4.895940769494517e-05,  1.481134121502096e-04,  9.988464273807826e-01,
          1.003087120708442e-01,  0.000000000000000e+00,  9.654908702179095e-05],
        [ 2.004542539326073e-07,  1.503607374785846e-03, -1.150494092148706e-02,
          9.999995990914922e-01,  0.000000000000000e+00, -4.520263559985373e-06],
        [-5.000740076693791e-02, -2.800480485142628e-03,  6.954027534561388e-05,
          9.700007269844974e-05,  1.000000000000000e+00, -2.418054601647726e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [136]:
# Bmad Jacobian
bend_tao = tao.matrix(0,1)
mat_tao = torch.tensor(bend_tao['mat6'])
mat_tao

tensor([[ 9.998962570786490e-01,  1.002675260014650e-01, -1.503457016141090e-03,
          2.199767517128930e-06,  0.000000000000000e+00,  2.209264164503290e-03],
        [-1.500165222074270e-02,  9.985994918154740e-01,  2.219540412090530e-05,
          4.895157360673540e-05,  0.000000000000000e+00,  4.997945455841130e-02],
        [-4.895940769494520e-05,  1.481134121502100e-04,  9.988464273807830e-01,
          1.003087120708440e-01,  0.000000000000000e+00,  9.654908702179100e-05],
        [ 2.004542539326070e-07,  1.503607374785850e-03, -1.150494092148710e-02,
          9.999995990914921e-01,  0.000000000000000e+00, -4.520263559985370e-06],
        [-5.000741235840330e-02, -2.805000346084490e-03,  7.859525469519101e-05,
          9.700067390706751e-05,  1.000000000000000e+00, -2.417366994909980e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [137]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=2.0e-1)

True

## Hard fringe exit

In [138]:
# Create bend
hard2 = SBend(L = 0.1,
              P0C = p_in.p0c,
              G = 0.5,
              DG = 0.0,
              E1 = 0.0,
              E2 = 0.02,
              FINT = 0.0,
              HGAP = 0.00,
              FINTX = 0,
              HGAPX = 0,
              FRINGE_AT = "exit_end",
              FRINGE_TYPE = "hard_edge_only"
             )
hard2

SBend(L=0.1, P0C=tensor(4.000000000000000e+07, dtype=torch.float64), G=0.5, DG=0.0, E1=0.0, E2=0.02, FINT=0.0, HGAP=0.0, FINTX=0, HGAPX=0, FRINGE_AT='exit_end', FRINGE_TYPE='hard_edge_only', TILT=0.0)

### One particle test

In [139]:
# Outgoing particle
p_out = track_element(p_in, hard2)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.290857559360805e-03, 2.868997890418367e-03, -3.100307067512662e-03,
        -9.734513263146211e-04, 1.892098440091584e-03, -2.000000000000002e-03],
       dtype=torch.float64)

In [140]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_bend_hard_exit.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [141]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.290857559360810e-03, 2.868997890418570e-03, -3.100307067512660e-03,
        -9.734513263146220e-04, 1.892098440805610e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [142]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=1e-12, rtol = 1e-14)

True

### Jacobian test

In [143]:
f_bend = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), hard2)[:6]
J = jacobian(f_bend, diff_coords)

In [144]:
# Jacobian matrix
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.988931713303267e-01,  1.002673469850181e-01,  1.553882237915952e-03,
          1.580857061508531e-04,  0.000000000000000e+00,  2.216097832943017e-03],
        [-1.499988763443865e-02,  9.996023117058469e-01, -1.942387249146361e-07,
          4.946078378709275e-05,  0.000000000000000e+00,  5.000153483463163e-02],
        [-4.945875175575238e-05, -2.744171583866144e-06,  9.999995403051171e-01,
          1.003085472687129e-01,  0.000000000000000e+00,  1.004686315159357e-04],
        [ 2.353580236415848e-05, -1.553261146042840e-03, -8.563384399552718e-03,
          9.991414007985201e-01,  0.000000000000000e+00, -7.408984892277388e-05],
        [-4.997944661507031e-02, -2.798462226675241e-03, -4.449394889299223e-06,
          1.000218244124947e-04,  1.000000000000000e+00, -2.417808294212509e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [145]:
# Bmad Jacobian
bend_tao = tao.matrix(0,1)
mat_tao = torch.tensor(bend_tao['mat6'])
mat_tao

tensor([[ 9.988931713303270e-01,  1.002673469850180e-01,  1.553882237915950e-03,
          1.580857061508530e-04,  0.000000000000000e+00,  2.216097832943020e-03],
        [-1.499988763443360e-02,  9.996023117058470e-01, -1.942387249146360e-07,
          4.946078378709300e-05,  0.000000000000000e+00,  5.000153483463180e-02],
        [-4.945875175575240e-05, -2.744171583866140e-06,  9.999995403051170e-01,
          1.003085472687130e-01,  0.000000000000000e+00,  1.004686315159360e-04],
        [ 2.353580236416020e-05, -1.553261146042840e-03, -8.563384399552620e-03,
          9.991414007985200e-01,  0.000000000000000e+00, -7.408984892277390e-05],
        [-4.997943426870830e-02, -2.798460986295760e-03, -4.467467887794670e-06,
          1.000192960365800e-04,  1.000000000000000e+00, -2.415734069078430e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [146]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-2)

True

# Sextupole tests

In [147]:
# Create sextupole
from bmadx.structures import Sextupole

sxtpl = Sextupole(
    L = 0.1,
    K2 = 10.0,
    NUM_STEPS = 5
)
sxtpl

Sextupole(L=0.1, K2=10.0, NUM_STEPS=5, X_OFFSET=0.0, Y_OFFSET=0.0, TILT=0.0)

## Sextupole one particle test

In [148]:
# Outgoing particle
p_out = track_element(p_in, sxtpl)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.300097668385619e-03, 3.002375257172364e-03, -3.100249396446189e-03,
        -1.006460289609605e-03, 1.999967267186112e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [149]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_sextupole.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [150]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.300722828854150e-03, 3.002336280079460e-03, -3.100519427866320e-03,
        -1.006561711070080e-03, 1.999464576378210e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [151]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

False

In [152]:
# kind of close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-3)

True

## Sextupole Jacobian test

In [153]:
# autodiff Jacobian matrix
f_sxtpl = lambda x: track_element(Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2), sxtpl)[:6]

J = jacobian(f_sxtpl, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 9.999174357547901e-01,  9.999830059523201e-02, -1.210425426630371e-04,
         -2.436898930899204e-06,  0.000000000000000e+00, -9.786516691184767e-08],
        [-2.124158062452428e-03,  9.999126249850201e-01, -3.046137894673759e-03,
         -1.226487047563603e-04,  0.000000000000000e+00, -2.380124295159301e-06],
        [-1.210425966319858e-04, -2.436899110779344e-06,  1.000082566414937e+00,
          1.000016994135919e-01,  0.000000000000000e+00,  2.498978986069283e-07],
        [-3.046144640173718e-03, -1.226487587148956e-04,  2.124378592369612e-03,
          1.000087377257244e+00,  0.000000000000000e+00,  6.473405792825830e-06],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  1.000000000000000e+00,  1.641561193496359e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [154]:
# Bmad formula Jacobian
sxtpl_tao = tao.matrix(0,1)
mat_tao = torch.tensor(sxtpl_tao['mat6'])
mat_tao

tensor([[ 9.998949838139880e-01,  1.001983563426460e-01, -1.519118520767270e-04,
         -5.202875386824220e-06,  0.000000000000000e+00, -3.013230408531040e-04],
        [-2.150105518146590e-03,  9.998895600666280e-01, -3.050200806818500e-03,
         -1.537229402602310e-04,  0.000000000000000e+00,  1.777161443576140e-07],
        [-1.519102303694520e-04, -5.202878468279730e-06,  1.000105027257950e+00,
          1.002044602530170e-01,  0.000000000000000e+00,  1.007400815178300e-04],
        [-3.050213452397130e-03, -1.537250762985790e-04,  2.150579831127880e-03,
          1.000110451350340e+00,  0.000000000000000e+00,  5.731379441954710e-07],
        [ 1.629871652728940e-07, -3.013230529168600e-04,  5.625742277080250e-07,
          1.007400986059620e-04,  1.000000000000000e+00,  1.742301912282970e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [155]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-14)

False

In [156]:
# kind of close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1e-3)

False

In [157]:
# matrix elements that fail
torch.isclose(mat_py, mat_tao, atol=0, rtol=1e-1)

tensor([[ True,  True, False, False,  True, False],
        [ True,  True,  True, False,  True, False],
        [False, False,  True,  True,  True, False],
        [ True, False,  True,  True,  True, False],
        [False, False, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True]])

## Sextupole offset test

In [158]:
# Create quad with offsetss
sxtpl_offset = Sextupole(
    L = 0.1,
    K2 = 10.0,
    X_OFFSET = 1e-3,
    Y_OFFSET = -2e-3
)
sxtpl_offset

Sextupole(L=0.1, K2=10.0, NUM_STEPS=1, X_OFFSET=0.001, Y_OFFSET=-0.002, TILT=0.0)

In [159]:
# Outgoing particle no offset
p_out = track_element(p_in, sxtpl)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.300097668385619e-03, 3.002375257172364e-03, -3.100249396446189e-03,
        -1.006460289609605e-03, 1.999967267186112e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [160]:
# Outgoing particle offset
p_out = track_element(p_in, sxtpl_offset)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.300000000000000e-03, 3.000000000000000e-03, -3.100000000000000e-03,
        -1.001002004008016e-03, 1.999967267186112e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [161]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_sextupole_offset.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [162]:
# Bmad outgoing particle
x_tao = torch.tensor([orbit_out['x'],
                      orbit_out['px'],
                      orbit_out['y'],
                      orbit_out['py'],
                      orbit_out['z'],
                      orbit_out['pz']], dtype=torch.double)
x_tao

tensor([2.300602711603240e-03, 2.999879746214770e-03, -3.100251004319680e-03,
        -1.001215494719830e-03, 1.999465207175330e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [163]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

False

In [164]:
# kind of close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-3)

True

In [165]:
# autodiff Jacobian matrix
f_sxtpl_off = lambda x: track_element(
    Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2),
    sxtpl_offset
)[:6]

J = jacobian(f_sxtpl_off, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 1.000000000000000e+00,  1.000000000000000e-01,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [-1.002004008016032e-03,  1.000000000000000e+00, -1.002004008016032e-03,
          0.000000000000000e+00,  0.000000000000000e+00, -0.000000000000000e+00],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00,
          1.000000000000000e-01,  0.000000000000000e+00,  0.000000000000000e+00],
        [-1.002004008016032e-03,  0.000000000000000e+00,  1.002004008016032e-03,
          1.000000000000000e+00,  0.000000000000000e+00,  1.004012032080192e-06],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  1.000000000000000e+00,  1.641561193496359e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [166]:
# Bmad formula Jacobian
sxtpl_tao = tao.matrix(0,1)
mat_tao = torch.tensor(sxtpl_tao['mat6'])
mat_tao

tensor([[ 9.999498992463300e-01,  1.002018093030550e-01, -5.010105563286550e-05,
         -3.019626757400920e-07,  0.000000000000000e+00, -3.012081463154540e-04],
        [-1.150241213732660e-03,  9.999348387936740e-01, -1.050120483022470e-03,
         -5.512293159051840e-05,  0.000000000000000e+00,  1.406143546315000e-07],
        [-5.010035130481110e-05, -3.019626757400920e-07,  1.000050100653270e+00,
          1.002010045722980e-01,  0.000000000000000e+00,  1.004529167962040e-04],
        [-1.050130520783950e-03, -5.512376702690520e-05,  1.150361498192750e-03,
          1.000065161015240e+00,  0.000000000000000e+00,  2.310269507332220e-07],
        [ 1.003776147596250e-07, -3.012081463154540e-04,  2.008305315558290e-07,
          1.004529167962040e-04,  1.000000000000000e+00,  1.742175310540000e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [167]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-14)

False

In [168]:
# kind of close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-3)

False

In [169]:
# matrix elements that fail
torch.isclose(mat_py, mat_tao, atol=0, rtol=1e-1)

tensor([[ True,  True, False, False,  True, False],
        [False,  True,  True, False,  True, False],
        [False, False,  True,  True,  True, False],
        [ True, False, False,  True,  True, False],
        [False, False, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True]])

## Sextupole tilt test (transverse rotation)

In [170]:
# Create quadrupole with tilt
sxtpl_tilt = Sextupole(
    L = 0.1,
    K2 = 10.0,
    TILT = 0.3)
sxtpl_tilt

Sextupole(L=0.1, K2=10.0, NUM_STEPS=1, X_OFFSET=0.0, Y_OFFSET=0.0, TILT=0.3)

In [171]:
# Outgoing particle no tilt
p_out = track_element(p_in, sxtpl)
x_py = torch.hstack(p_out[:6])
x_py

tensor([2.300097668385619e-03, 3.002375257172364e-03, -3.100249396446189e-03,
        -1.006460289609605e-03, 1.999967267186112e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [172]:
# Outgoing particle tilt
p_out = track_element(p_in, sxtpl_tilt)

x_py = torch.hstack(p_out[:6])
x_py

tensor([2.300000000000000e-03, 3.006266519417276e-03, -3.099999999999999e-03,
        -1.001774892320196e-03, 1.999967267186112e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [173]:
# Bmad lattice to compare
tao = Tao('-lat '+repo_path+'/tests/bmad_lattices/test_sextupole_tilt.bmad -noplot')
tao.cmd('set particle_start x='+str(coords[0]))
tao.cmd('set particle_start px='+str(coords[1]))
tao.cmd('set particle_start y='+str(coords[2]))
tao.cmd('set particle_start py='+str(coords[3]))
tao.cmd('set particle_start z='+str(coords[4]))
tao.cmd('set particle_start pz='+str(coords[5]))
orbit_out = tao.orbit_at_s(ele=1)

In [174]:
# Bmad outgoing particle
x_tao = torch.tensor(
    [orbit_out['x'],
     orbit_out['px'],
     orbit_out['y'],
     orbit_out['py'],
     orbit_out['z'],
     orbit_out['pz']], dtype=torch.double
)
x_tao

tensor([2.300916042099510e-03, 3.006591889759490e-03, -3.100289649913260e-03,
        -1.002257281145800e-03, 1.999464226059350e-03, -2.000000000000000e-03],
       dtype=torch.float64)

In [175]:
# close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-14)

False

In [176]:
# kind of close to Tao result?
torch.allclose(x_py, x_tao, atol=0, rtol=1.0e-3)

True

In [177]:
# autodiff Jacobian matrix
f_sxtpl_tilt = lambda x: track_element(
    Particle(*x, s=p_in.s, p0c=p_in.p0c, mc2=p_in.mc2),
    sxtpl_tilt
)[:6]

J = jacobian(f_sxtpl_tilt, diff_coords)
mat_py = torch.vstack(J)
mat_py

tensor([[ 1.000000000000000e+00,  1.000000000000000e-01,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00],
        [ 1.108978749840803e-03,  1.000000000000000e+00, -3.438360444956874e-03,
          0.000000000000000e+00,  0.000000000000000e+00, -6.279077572420955e-06],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00,
          1.000000000000000e-01,  0.000000000000000e+00,  0.000000000000000e+00],
        [-3.438360444956874e-03,  0.000000000000000e+00, -1.108978749840803e-03,
          1.000000000000000e+00,  0.000000000000000e+00,  1.778449218632936e-06],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  1.000000000000000e+00,  1.641561193496359e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [178]:
# Bmad formula Jacobian
sxtpl_tao = tao.matrix(0,1)
mat_tao = torch.tensor(sxtpl_tao['mat6'])
mat_tao

tensor([[ 1.000055450237350e+00,  1.002018121746740e-01, -1.719202764607350e-04,
         -3.023939511674620e-07,  0.000000000000000e+00, -3.015221137976090e-04],
        [ 1.052862644367350e-03,  1.000050014693330e+00, -3.580494475843810e-03,
         -1.868520004240650e-04,  0.000000000000000e+00, -3.378937529859550e-07],
        [-1.719192273213490e-04, -3.023939511709320e-07,  9.999445512466359e-01,
          1.002010056330370e-01,  0.000000000000000e+00,  1.004916421965590e-04],
        [-3.580529654996660e-03, -1.868532025687820e-04, -1.052166109251760e-03,
          9.999499868370290e-01,  0.000000000000000e+00,  5.121106595242230e-07],
        [-3.392741440886320e-07, -3.015221137976090e-04,  4.617240082008190e-07,
          1.004916421965590e-04,  1.000000000000000e+00,  1.742371929933270e-05],
        [ 0.000000000000000e+00,  0.000000000000000e+00,  0.000000000000000e+00,
          0.000000000000000e+00,  0.000000000000000e+00,  1.000000000000000e+00]],
       dtype=torch.fl

In [179]:
# close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-14)

False

In [180]:
# kind of close to Tao result?
torch.allclose(mat_py, mat_tao, atol=0, rtol=1.0e-3)

False

In [181]:
# matrix elements that fail
torch.isclose(mat_py, mat_tao, atol=0, rtol=1e-1)

tensor([[ True,  True, False, False,  True, False],
        [ True,  True,  True, False,  True, False],
        [False, False,  True,  True,  True, False],
        [ True, False,  True,  True,  True, False],
        [False, False, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True]])